import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBer from "../components/shared/navber";
import Footer from "../components/shared/footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">  


        <Toaster 
          position="bottom-right" 
          toastOptions={{
            style: {
              background: '#0b0f19',
              color: '#fff',
              border: '1px solid #161c2e',
            },
          }}
        />     
        <NavBer></NavBer>
        
        
        <div>
          {children}
        </div>

        <Footer></Footer>

        </body>
    </html>
  );
}
